config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  resources :bookings, except: [:show] 
  resources 'reports'
  resources 'statistics'

  get 'verificar', to: "bookings#verificar"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :nombre, :telefono, :fecha, :hora, presence: true
  validates :fecha, uniqueness: { scope: :hora, 
    message: "u hora no disponibles!" } 
  validates :telefono, :length => { :is => 8, 
    message: " debe tener 8 digitos."} 

  # busquedas 
  def self.search(search)
    if search 
      where(["fecha = ?", "#{search}"])
    else
      Booking.all 
    end 
  end     

  def self.searchr(s,e)
    where("fecha BETWEEN ? AND ?", s, e)
  end 
  #busquedas 

  def self.verificar(fecha, hora)
    where("fecha = ? and hora = ?", fecha, hora).empty?
  end 

  #dia con mas partidos 
  def self.dia 
    dias = group(:fecha).count(:fecha)
    dias.values.max
  end 

  #record reservaciones 
  def self.dia_max 
    dias = group(:fecha).count(:fecha)
    dias.max_by{|k,v| v}[0]
  end 

  #hora mas reservada
  def self.hora_pref
    horas =  group(:hora).count(:hora)
    horas.max_by{|k,v| v}[0]
  end 

  #partidos para el dia actual 
  def self.reservas_hoy
    where("fecha = ?", Date.today).count
  end 

  #ultimos 7 dias 
  def self.reservas_l
    where("fecha > ?", Date.today-7.days).count
  end 

  #proximos 7 dias 
  def self.reservas_n
    where("fecha BETWEEN ? AND ?", Date.today, Date.today+7.days).count
  end 

  
  before_save :pago_monto 

  def pago_monto
    if completado == false 
      self.monto = 0
    else 
      if self.hora > 18 
        self.monto = 180
      else 
        self.monto = 150
      end
    end 
  end 


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :index]
  
  def index 
    @reservas = Booking.search(params[:search]).order("fecha DESC").paginate(page: params[:page], per_page: 6)
  end  

  def verificar 
    verf = Booking.where("fecha = ? and hora = ?", params[:fecha], params[:hora]).empty?
    if verf == true 
      redirect_to root_path
      flash[:notice] = "¡DISPONIBLE!"
    else
      redirect_to root_path
      flash[:notice] = "Lo sentimos, no esta disponible..."
    end  
  end 

  #crear 
  def new 
    @reserva = Booking.new 
  end 

  def create 
    @reserva = Booking.create(booking_params)
    if @reserva.save  
      flash[:notice] = "¡Reservación exitosa! Total a cancelar Q#{@reserva.monto}"
      redirect_to root_path
    else
        flash.now[:notice] = @reserva.errors.full_messages[0]
        render 'new'
    end  
  end 

  #actualizar 
  def edit 
  end 

  def update 
    if @reserva.update(booking_params)
      flash[:notice] = "¡Reservación actualizada!"
      redirect_to bookings_path
    else
      flash.now[:notice] = @reserva.errors.full_messages[0]
      render 'edit'
    end 
  end 

  #eliminar 
  def destroy 
    @reserva.destroy 
    redirect_to bookings_path
  end 

  private 
  def booking_params
      params.require(:booking).permit(:nombre, :telefono, :fecha, :hora, :completado, :monto)      
  end

  def set_booking
      @reserva = Booking.find(params[:id])
  end

end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController 
  def home 
  end
   
end 

app/controllers/reports_controller.rb
class ReportsController < ApplicationController 
  before_action :authenticate_user!
  
  def index 
    @reservas = Booking.searchr(params[:s], params[:e]).order("fecha DESC").paginate(page: params[:page], per_page: 5) 
  end 
  
end 

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController 
  before_action :authenticate_user!

  def index 
    @reservas = Booking.all 
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<section class="hero is-primary fondo">
    <div class="columns is-vcentered formulario my-3">
    <br>
    <br>
        <div class="column"></div>
        <div class="column my-6 has-text-centered has-background-white">
            <p class="subtitle is-4 has-text-dark">Hacer una reservación</p>
            <hr>
            <%= form_for @reserva do |f| %>
            <div class="field">
                <label class="label">Nombre y apellido</label>
                <div class="control">
                    <%= f.text_field :nombre, autofocus: true, class: "input"%>
                </div>
            </div> 
            <br>
            <div class="field">
                <label class="label">Telefono</label>
                <div class="control">
                    <%= f.number_field :telefono, autofocus: true, class: "input"%>
                </div>
            </div>
            <br>
            <div class="columns">
                <div class="column">            
                    <div class="field">
                        <label class="label">Fecha</label>
                        <div class="control">
                            <%= f.date_field :fecha, autofocus: true, class: "date input"%>
                        </div>
                    </div>
                </div>
                <div class="column">               
                    <div class="field">
                        <label class="label">Hora</label>
                        <div class="control">
                            <%= f.time_field :hora, autofocus: true, class: "input", value: "15:00:00", max: "23:00:00", min: "07:00:00", step: "1"%>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="columns mb-2">
                <div class="column">
                    <div class="control">
                        <%= f.submit(@reserva.new_record? ? "Reservar" : "Actualizar", class: "button is-link is-fullwidth", data: {confirm: "Una vez hecha la reservación no podrás cancelar ¿Deseas continuar?"})%>
                    </div>
                </div>
                <div class="column">
                    <div class="control">
                        <% if user_signed_in? %>
                            <%= link_to "Cancelar", bookings_path, class: "button is-danger is-light is-fullwidth" %>
                        <% else %>
                            <%= link_to "Cancelar", root_path, class: "button is-danger is-light is-fullwidth" %>
                        <% end %>
                    </div>    
                </div>
            </div>
            <% end %>
        </div>
        <div class="column"></div>
    </div>
</section>

app/views/bookings/edit.html.erb
<%= render 'form', reserva: @reserva %>

app/views/bookings/index.html.erb
<section class="hero">
    <div class="columns my-3">
        <div class="column"></div>
        <div class="column is-four-fifths">
            <p class="subtitle is-2 has-text-centered">Todas las reservaciones <%= link_to "", new_booking_path, class: "mdi mdi-plus-circle-multiple-outline has-text-primary mdi-36px limpiar" %></p>
            <div class="container">
                <div class="field is-pulled-left">
                    <div class="tags are-medium has-addons">
                        <span class="tag my-1">Reservaciones</span>
                        <span class="tag is-primary my-1"><%= @reservas.count %></span>
                        <span class="tag my-1">Ganancias</span>
                        <span class="tag is-primary my-1">Q<%= @reservas.sum(:monto) %></span>
                    </div>
                </div>
                <div class="field is-pulled-right">
                    <%= form_tag bookings_path, method: :get do %>
                    <div class="field has-addons">
                        <div class="control">
                            <%= date_field_tag :search, params[:search], placeholder: "dd/mm/aaa", class: "input"%>
                        </div>
                        <div class="control">
                            <%= submit_tag "Buscar por fecha", class: "mdi mdi-search button is-primary"%>
                            <%= link_to "", bookings_path, class: "mdi mdi-broom has-text-dark mdi-24px limpiar" %>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <br>
            <br>
            <table class="table is-fullwidth is-striped">
                <thead>
                    <tr>    
                        <th>Completado</th>
                        <th>Responsable</th>
                        <th>Telefono</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Monto</th>
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <% @reservas.each do |reserva| %>
                    <tr>    
                        <td><%= check_box_tag nil, nil, reserva.completado?, data: {reflex: "click->CompletadoReflex#complet", id: reserva.id}%></td>
                        <td><%= reserva.nombre%></td>
                        <td><%= reserva.telefono%></td>
                        <td><%= reserva.fecha.strftime("%d/%m/%Y")%></td>
                        <td><%= reserva.hora%></td>
                        <td>Q<%= reserva.monto%></td>
                        <td><%= link_to "Editar", edit_booking_path(reserva), class: "button is-warning is-small is-rounded btn-accion"%></td>
                        <td><%= link_to "Eliminar", booking_path(reserva), method: :delete, class: "button is-danger is-small is-rounded btn-accion", data: {confirm: "Deseas eliminar esta reservación?"}%></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <div>
                <%= will_paginate @reservas, renderer: BulmaPagination::Rails, :previous_label => t("anterior"), :next_label => t("siguiente"), class: 'is-rounded is-centered' %>
            </div>
        </div>
        <div class="column"></div>
    </div>
</section>

app/views/bookings/new.html.erb
<%= render 'form', reserva: @reserva %>

app/views/layouts/_messages.html.erb
<div class="container-fluid alerta" id="alerta">
    <% flash.each do |name, msg| %>
      <div class="notification is-info is-light" role="alert">
          <%= msg %>   
      </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="#">
      <img src="https://image.flaticon.com/icons/svg/3203/3203244.svg" width="120" height="32">
    </a>

    <span class="navbar-burger burger" data-target="navMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </span>
  </div>

  <div id="navMenu" class="navbar-menu">
    <% if user_signed_in? %>
    <div class="navbar-start">
      <%= link_to "Inicio", root_path, class: "navbar-item btn-nav" %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">Administrar</a>
        <div class="navbar-dropdown">
            <%= link_to "Reservaciones", bookings_path, class: "navbar-item" %>
            <%= link_to "Estadisticas", statistics_path, class: "navbar-item" %>
            <%= link_to "Reportes", reports_path, class: "navbar-item" %>
        </div>
      </div>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to "Salir", destroy_user_session_path, method: :delete, class: "button is-danger is-outlined" %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="navbar-start">
      <%= link_to "Inicio", root_path, class: "navbar-item btn-nav" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <%= link_to "Admin", new_user_session_path, class: "button is-light" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Reserva_me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>   
  </body>
</html>

app/views/pages/home.html.erb
<section class="hero fondo">
  <div class="hero-body has-text-centered">
    <div class="container">
        <p class="subtitle is-1 my-0 has-text-centered has-text-light has-text-weight-bold titulo">Cancha Sintentica</p>
        <p class="subtitle is-3 has-text-centered has-text-light titulo">Cantón Reforma, San Antonio Huista</p>
        <div class="hero my-3">
            <div class="field is-pulled-right">
                <%= form_tag url_for(controller: 'bookings', action: 'verificar'), method: "get" do %>
                <div class="field has-addons is-pulled-right">
                    <div class="control">
                        <%= date_field_tag :fecha, params[:fecha], placeholder: "dd/mm/aaa", class: "input"%>
                    </div>
                    <div class="control">
                        <%= number_field_tag :hora, params[:hora], placeholder: "hora", class: "input"%>
                    </div>
                    <div class="control">
                        <%= submit_tag "¿esta disponible?", class: "mdi mdi-search button is-dark is-light"%>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="columns">
            <div class="column">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                        </figure>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                        </figure>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                        </figure>
                    </div>
                </div>
            </div>
        </div>
        <%= link_to "RESERVAR", new_booking_path, class: "button is-rounded is-light is-outlined is-centered is-large my-2 reserva" %>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<section class="hero">
    <div class="columns my-3">
        <div class="column"></div>
        <div class="column is-three-quarters">
            <p class="subtitle is-2 has-text-centered">Reportes</p>
            <div class="container">
                <div class="field is-pulled-left">
                    <div class="tags are-medium has-addons">
                        <span class="tag my-1">Reservaciones</span>
                        <span class="tag is-success my-1"><%= @reservas.count %></span>
                        <span class="tag my-1">Ganancias</span>
                        <span class="tag is-success my-1">Q<%= @reservas.sum(:monto) %></span>
                    </div>
                </div>
                <div class="field is-pulled-right">
            <!--<%= link_to "Exportar a PDF", root_path, class: "button is-primary"%>-->
                <%= form_tag reports_path, method: :get do %>
                <div class="field has-addons">
                    <div class="control">
                        <%= date_field_tag :s, params[:s], placeholder: "Inicio", class: "input" %>
                    </div>
                    <div class="control">
                        <%= date_field_tag :e, params[:e], placeholder: "Fin", class: "input" %>
                    </div>
                    <div class="control">
                        <%= submit_tag "Buscar por rango", class: "mdi mdi-search button is-success"%>
                        <%= link_to "", reports_path, class: "mdi mdi-broom has-text-dark mdi-24px limpiar" %>
                    </div>
                </div>
                <% end %>
                </div>
            </div>
            <br>
            <br>
            <table class="table is-fullwidth is-striped">
                <thead>
                    <tr>
                        <th>Completado</th>
                        <th>Responsable</th>
                        <th>Telefono</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Monto</th>
                        <th colspan="2">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <% @reservas.each do |reserva| %>
                    <tr>
                        <td><%= check_box_tag nil, nil, reserva.completado?, data: {reflex: "click->CompletadoReflex#complet", id: reserva.id}, class: "reports"%></td>
                        <td><%= reserva.nombre%></td>
                        <td><%= reserva.telefono%></td>
                        <td><%= reserva.fecha.strftime("%d/%m/%Y")%></td>
                        <td><%= reserva.hora%></td>
                        <td>Q<%= reserva.monto%></td>
                        <td><%= link_to "Editar", edit_booking_path(reserva), class: "button is-warning is-small is-rounded btn-accion"%></td>
                        <td><%= link_to "Eliminar", booking_path(reserva), method: :delete, class: "button is-danger is-small is-rounded btn-accion", data: {confirm: "¿Desea eliminar la reservación de #{reserva.nombre}?"}%></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <div>
                <%= will_paginate @reservas, renderer: BulmaPagination::Rails, :previous_label => t("anterior"), :next_label => t("siguiente"), class: 'is-rounded is-centered' %>
            </div>
        </div>
        <div class="column"></div>
    </div>
</section>

app/views/statistics/index.html.erb
<section class="hero">
    <div class="columns my-3">
        <div class="column is-full">
            <p class="subtitle is-2 has-text-centered">Estadisticas</p>
            <div class="container">
            <%= area_chart Booking.group_by_day(:fecha).count, colors: ["#1BA9A9", "#8E44AD"] %>                
            </div>
                <div class="columns mx-2 my-2">
                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Día con mas reservaciones</p>
                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered first"><%= @reservas.dia_max.strftime("%d/%m/%Y")%></p>
                            </div>
                        </div>
                    </div>

                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Hora de reservaciones preferida</p>
                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered"><%= @reservas.hora_pref%></p>
                            </div>
                        </div>
                    </div>

                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Máximo de reservaciones en un día</p>  
                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered"><%= @reservas.dia%></p>
                            </div>
                        </div>
                    </div>
                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Reservaciones para hoy</p>
                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered"><%= @reservas.reservas_hoy%></p>
                            </div>
                        </div>
                    </div>
                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Reservaciones en los últimos 7 días</p>
                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered"><%= @reservas.reservas_l%></p>
                            </div>
                        </div>
                    </div>
                    <div class="column is-2">
                        <div class="card has-text-black">
                            <div class="card-header">
                                <div class="card-header-title has-text-black">
                                <p>Reservaciones en los próximos 7 días</p>                                </div>
                            </div>
                            <div class="card-content">
                                <p class="has-text-centered"><%= @reservas.reservas_n%></p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
</section>